### PR TITLE
Replaced the old cover image with the new one

### PR DESCRIPTION
**Pull request by rdev12**
Replaced with the image given by @debarghya472

### CODE REVIEW

**Review by debarghya472 — CHANGES_REQUESTED** [review]
take the screenshot of Cover photo.png file present in the home directory

**Comment by rdev12** [comment]
image

**Review by debarghya472 — COMMENTED** [review]
Also You need to create a new branch every time since its your first hand experience and are prone to errors.

**Comment by rdev12** [comment]
Just in case you were wondering, it was initially a jpg file so I replaced it with a jpg file too

**Comment by debarghya472** [comment]
Thats fine !!

**Comment by rdev12** [comment]
> Also You need to create a new branch every time since its your first hand experience and are prone to errors.

Do you mean I shouldn't make any changes in the master of my fork?

**Comment by debarghya472** [comment]
Yes u should always create a new branch and then add ur changes. It seems that u haven't committed ur changes properly. It shows Cover Photo.jpg deleted but no new file was added.

**Comment by rdev12** [comment]
> Yes u should always create a new branch and then add ur changes. It seems that u haven't committed ur changes properly. It shows Cover Photo.jpg deleted but no new file was added.

It shows that I have replaced. Take a look:
image

**Pull request closed without merging**
